### ISSUE TITLE
init .clang-format [2]

### ISSUE THREAD

**Issue by shinarove** [PM4-FS25-DungeonCrawl/DungeonCrawl#36]
.clang-format kann GitHub Actions übergeben werden um z.B. Datei automatisch korrekt zu formatieren:

Beispiel eines yaml für automatische Formatierung

```yaml
name: Auto Clang-Format

on: [push, pull_request]

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Clang-Format
        run: sudo apt-get install -y clang-format

      - name: Format Code
        run: |
          find . -name '*.cpp' -o -name '*.h' | xargs clang-format -i

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff --staged --quiet || git commit -m "Auto-format code"
          git push
```

Die .clang-format datei könnte wie folgt aus schauen:

```yaml
BasedOnStyle: LLVM
IndentWidth: 4
UseTab: Never
BreakBeforeBraces: Allman
SpaceBeforeParens: ControlStatements
ColumnLimit: 0
```
